### ISSUE TITLE
Recommend posting an example EC2 Activity Worker in Python

### ISSUE THREAD

**Issue by andrew6850** [awsdocs/aws-step-functions-developer-guide#10]
Hi Docs Team,

It took me quite awhile to get a Python EC2 Activity Worker going - an example would be very helpful.  I can't read Ruby (yet), and luckily I stumbled upon a Java example that got me closer.  Here is what I ended up with for a basic (functional) Python example.  It could be made way better in many ways, but it does seem to work:

https://stackoverflow.com/questions/52915690/step-functions-activity-worker-best-practice-for-handling-long-polling-timeout/52968269#52968269

What led me astray was how the Boto3 docs reference a null string being returned in the response (when no activities are in the Step Functions Queue). I was looking for a Key: Value pair with no value, but really it seems that the Step Functions response does not include the taskToken key either.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html#SFN.Client.get_activity_task

"The maximum time the service holds on to the request before responding is 60 seconds. If no task is available within 60 seconds, the poll returns a taskToken with a null string."

Thanks,
Andrew
aetroup@

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
