### ISSUE TITLE
Lack of examples for Bigdata services' Boto3 API calls  in the official AWS documentation

### ISSUE THREAD

**Issue by Karan970** [awsdocs/aws-step-functions-developer-guide#13]

**Comment by Karan970** [comment]
Example, create_script of glue boto3 API requires a DAG as a parameter there is no elaboration on how to provide it

**Comment by AdemolaAfolabi** [comment]
@Karan970 
{
    "DagEdges": [
        {
            "Source": "datasource0",
            "TargetParameter": "frame",
            "Target": "applymapping1"
        },
        {
            "Source": "dropnullfields3",
            "TargetParameter": "frame",
            "Target": "datasink4"
        },
        {
            "Source": "resolvechoice2",
            "TargetParameter": "frame",
            "Target": "dropnullfields3"
        },
        {
            "Source": "applymapping1",
            "TargetParameter": "frame",
            "Target": "resolvechoice2"
        }
    ],
    "DagNodes": [
        {
            "Args": [
                {
                    "Param": false,
                    "Name": "database",
                    "Value": "\"government\""
                },
                {
                    "Param": false,
                    "Name": "table_name",
                    "Value": "\"germany_gdp_csv\""
                },
                {
                    "Param": false,
                    "Name": "transformation_ctx",
                    "Value": "\"datasource0\""
                }
            ],
            "NodeType": "DataSource",
            "Id": "datasource0",
            "LineNumber": 16
        },
        {
            "Args": [
                {
                    "Param": false,
                    "Name": "mapping",
                    "Value": "[(\"date\", \"string\", \"date\", \"string\"), (\"value\", \"double\", \"value\", \"double\")]"
                },
                {
                    "Param": false,
                    "Name": "transformation_ctx",
                    "Value": "\"applymapping1\""
                }
            ],
            "NodeType": "ApplyMapping",
            "Id": "applymapping1",
            "LineNumber": 21
        },
        {
            "Args": [
                {
                    "Param": false,
                    "Name": "catalog_connection",
                    "Value": "\"MySQL Connection\""
                },
                {
                    "Param": false,
                    "Name": "connection_options",
                    "Value": "{\"dbtable\": \"germany_gdp_csv\", \"database\": \"glue\"}"
                },
                {
                    "Param": false,
                    "Name": "transformation_ctx",
                    "Value": "\"datasink4\""
                }
            ],
            "NodeType": "DataSink",
            "Id": "datasink4",
            "LineNumber": 36
        },
        {
            "Args": [
                {
                    "Param": false,
                    "Name": "transformation_ctx",
                    "Value": "\"dropnullfields3\""
                }
            ],
            "NodeType": "DropNullFields",
            "Id": "dropnullfields3",
            "LineNumber": 31
        },
        {
            "Args": [
                {
                    "Param": false,
                    "Name": "choice",
                    "Value": "\"make_cols\""
                },
                {
                    "Param": false,
                    "Name": "transformation_ctx",
                    "Value": "\"resolvechoice2\""
                }
            ],
            "NodeType": "ResolveChoice",
            "Id": "resolvechoice2",
            "LineNumber": 26
        }
    ]
}

**Comment by AdemolaAfolabi** [comment]
@Karan970 a good way to get a example is to generate a sample script from the console and use the get-dataflow-graph method to see the response.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
