### ISSUE TITLE
Parallel state documentation could be improved

### ISSUE THREAD

**Issue by benkehoe** [awsdocs/aws-step-functions-developer-guide#21]
The simplicity of the examples in the [Parallel state documentation page](https://github.com/awsdocs/aws-step-functions-developer-guide/blob/master/doc_source/amazon-states-language-parallel-state.md) led to some confusion among our developers. In particular, they were confused about the statement "A state in one branch of a Parallel state must not have a Next field that targets a field outside of that branch, nor can any other state outside the branch transition into that branch." When looking at the [accompanying image](https://camo.githubusercontent.com/59a01007f0b80923a30b66da9f1218610e6a634b/687474703a2f2f646f63732e6177732e616d617a6f6e2e636f6d2f737465702d66756e6374696f6e732f6c61746573742f64672f696d616765732f706172616c6c656c2d73746174652e706e67), which shows two branches, each with a single state (i.e., not having a Next state) and the Parallel state itself not having a Next state, they interpreted this as Parallel states being dead ends. I believe a more comprehensive example state machine could help clear up this confusion. We extended the documentation example with a few more states to help resolve the confusion, you can see it [here](https://files.slack.com/files-pri/TCDG60V32-FHQRQ4P4G/screen_shot_2019-04-09_at_5.52.58_pm.png). I think it would also be worth including a visual depiction of what state machine logic is *not* allowed (in that state machine, a connection between PutItem and LookupPhone or LookupName would not be allowed, nor between LookupAddress and LookupName).

Additionally, I believe it would be helpful in these diagrams to draw arrows from the last state in each branch to the Next state after the Parallel state, indicating that the output gets collected and passed; this mirrors the way the input to the parallel state is drawn to the starting state for each branch.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
