### ISSUE TITLE
Step Function does not get invoked from S3 in case of PutObject of a file bigger than the multipart upload

### ISSUE THREAD

**Issue by wenzaca** [awsdocs/aws-step-functions-developer-guide#24]
In case where the size of object is bigger than the multipart upload specified (or not, default 8MB in the PutObject request to S3, the API logged in CloudTrail will be CompleteMultipartUpload instead of PutObject, which may result in the non invocation of Step Functions. By that being said, a note have been added to inform customers about it.

**Comment by smckenzie23** [comment]
Thanks for your pull request. The note has been added and will show up in the public docs soon.
