### ISSUE TITLE
Unclear documentation regarding nested maps and lists in DDB integration.

### ISSUE THREAD

**Issue by sam-goodwin** [awsdocs/aws-step-functions-developer-guide#35]
On: https://github.com/awsdocs/aws-step-functions-developer-guide/blob/master/doc_source/connect-ddb.md

It's not clear what this statement means:

> You cannot pass a map or list to DynamoDB inside a map.

Specifically:
> inside a map

Inside a nested map attribute, or a Step Function Map task? Can I pass a map or list as a top-level attribute? Also, explain why ...

A consistent problem I see with AWS docs is that they only show simple cases. The examples should go a bit deeper.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
