### ISSUE TITLE
Add "best practices" notes around error handling with regards to user input

### ISSUE THREAD

**Issue by jpeddicord** [awsdocs/aws-step-functions-developer-guide#36]
Yesterday, I was working with Step Functions on a workflow that accepted user input and processed it. In several tasks, some validation activities occur, which can fail (due to user input). I've noticed, though experimentation and searching around, that this isn't really what workflows are meant for:

1. The Fail state in a definition cannot accept paths (`$`), only hard-coded strings. This implies that internal errors shouldn't "bubble up" to the end state.
2. A machine doesn't have an Error output, only individual tasks have that (which requires doing a history lookup).
3. It's near-impossible to return a "nice" error from a Lambda function. For example, if you're validating that a user entered a valid option, you can't just throw an e.g. ValidationError, as that'll end up with an error state with `{error: ValidationError, cause: a-very-long-string-with-a-json-serialized-stack-trace}`. (It _is_ possible to do this with an activity worker and manually calling SendTaskFailure -- but that's not a useful option when a task is directly running a function).

These, to me, very strongly suggests that error handling logic in a step functions definition should only be for unexpected errors, not those that can be handled with user input. Expected errors due to user input should (apparently) still result in successful workflows, unless I **really** missed some big feature somewhere.

If a section in the docs were added to address this, I bet it would save a lot of developers some time: https://docs.aws.amazon.com/step-functions/latest/dg/sfn-best-practices.html

If you'd like, I'm happy to discuss this internally (peddicor@) with doc writers and/or the service team.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
