### ISSUE TITLE
Manage a Batch Job (AWS Batch, Amazon SNS) is not working in cn-north-1 region

### ISSUE THREAD

**Issue by forhead** [awsdocs/aws-step-functions-developer-guide#37]
https://github.com/awsdocs/aws-step-functions-developer-guide/blob/master/doc_source/batch-job-notification.md

when I run the example project, meet error below issue in cloudformation stack. when I change the **ec2.amazonaws.com** to **ec2.amazonaws.com.cn**, it fixed. 

Invalid principal in policy: "SERVICE":"ec2.amazonaws.com" (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: f3de836d-ae63-4d59-95e1-d162d3031b72)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
