### ISSUE TITLE
Synchronous Express state machine execution does not work

### ISSUE THREAD

**Issue by benmcmeen** [awsdocs/aws-step-functions-developer-guide#42]
State machines called sync (EXPRESS), give strange error and modify URL that's used for local:

```
laptop$ aws stepfunctions --endpoint http://localhost:8083 create-state-machine --type "EXPRESS" --definition "{\
>   \"Comment\": \"A Hello World example of the Amazon States Language using an AWS Lambda Local function\",\
>   \"StartAt\": \"HelloWorld\",\
>   \"States\": {\
>     \"HelloWorld\": {\
>       \"Type\": \"Task\",\
>       \"Resource\": \"arn:aws:lambda:us-east-1:123456789012:function:HelloWorldFunction\",\
>       \"End\": true\
>     }\
>   }\
> }\
> }}" --name "HelloWorld" --role-arn "arn:aws:iam::012345678901:role/DummyRole"
{
    "stateMachineArn": "arn:aws:states:us-east-1:123456789012:stateMachine:HelloWorld2",
    "creationDate": "2020-12-07T16:12:18.496000-06:00"
}

laptop$ aws stepfunctions --endpoint http://localhost:8083 start-sync-execution --state-machine arn:aws:states:us-east-1:123456789012:stateMachine:HelloWorld2 --name test

Could not connect to the endpoint URL: "http://sync-localhost:8083/"
```

**Comment by benmcmeen** [comment]
OK - who maintains this jar?  The docker image in hub gets updated but there are never any changelogs.  It simply wraps this jar - which doesn't seem to be in a repo, so no changelog there either.  SYNC execution still doesn't work - please advise.  This pretty much makes local development with the container or localstack (which uses AWS' sfn container) - difficule.

**Comment by cgnhmt** [comment]
Having the same issue. Any update so far?

**Comment by benmcmeen** [comment]
Nope - our TAMs mentioned it would be taken care of earlier this year, but AWS is pretty unresponsive about this tool, and there isn't a way to ask the maintainer.  I actually have a test script that pulls the latest and runs a check for sync, I'll send an update here if AWS ever gets off center and fixes their stuff - and yes, I fully intend to be snarky and throw shade about it.

**Comment by cgnhmt** [comment]
Hi Ben, thanks for the quick reply! Totally agree with you that's pretty annoying issue. I was thinking if I do something wrong with the API calling but neither works with AWS CLI nor boto3. There must be a way to handle this. I wonder how AWS is handling this on production.

**Comment by benmcmeen** [comment]
In production it just works.  The sync operation looks like it goes through it's own VPCE maybe?  Locally it does not work - so we just call async and have a polling script to describe execution.  When it's done, we grab the output.  Our invoking code is littered with these conditions for our localstack environment.

**Comment by cgnhmt** [comment]
If I can't solve the issue, I will go with the same way probably using a activity tracker script. But it is totally mess imo. When prod and local envs are different having trouble soon in general. 

I have an assumption that the problem might be in the create-state-machine method for EXPRESS workflows.
When I create a state machine on my local and list them it doesn't show me the type of the SM. -->


**Local Env**
```python

{
    "stateMachines": [
        {
            "stateMachineArn": "arn:aws:states:***:***:stateMachine:express-try",
            "name": "express-try",
            "creationDate": "2021-11-05T17:41:48+01:00"
        }
    ]
}
```
**But on Production;**

```python
        {
            "stateMachineArn": "arn:aws:states:**: **:stateMachine:**",
            "name": "**-**",
            "type": "EXPRESS",
            "creationDate": "2021-10-25T17:54:13.474000+02:00"
        },
```
I followed this documentation to create "Express" state machines as explained [here] (https://docs.aws.amazon.com/cli/latest/reference/stepfunctions/create-state-machine.html#create-state-machine) with local endpoint.

**Comment by benmcmeen** [comment]
So... you can create EXPRESS locally.  But you will have to use the new CLI to specify the `type` (default is STANDARD): 

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/stepfunctions/create-state-machine.html

So locally you will have EXPRESS once you upgrade to that CLI, but you still won't be able to invoke the SFN with sync - because it's just not supported locally (and hasn't for the last 18 months I've been complaining about it).  You will probably need a local workaround to get your dev environment halfway usable until AWS fixes it.

**Comment by cgnhmt** [comment]
Now, I have tried again with the latest version of the AWS CLI but still on my local I am not able to create EXPRESS workflows. 
I created state machines with the same definition on production as "STANDARD" and "EXPRESS" but local does not get the **type** parameter on create-state-machine method. 

Thanks anyway @benmcmeen :)

**Comment by benmcmeen** [comment]
I do it all the time... try:

```
aws stepfunctions --endpoint-url http://localhost:4566 create-state-machine --definition "{\
  \"Comment\": \"A Hello World example of the Amazon States Language using a Pass state\",\
  \"StartAt\": \"HelloWorld\",\
  \"States\": {\
    \"HelloWorld2\": {\
      \"Type\": \"Pass\",\
      \"End\": true\
    }\
  }}" --name "HelloWorld" --type "EXPRESS" --role-arn "arn:aws:iam::000000000000:role/DummyRole"
  ```

If this _doesn't_ work - I'd make sure you are on a recent version of localstack.   Also, you cannot update a STANDARD state machine into EXPRESS, it needs to be deleted and recreated with the type.

I don't want to throw any cold water on your future plans, but if you use Terraform prepare for it to let you down with it's SFN provider.  There are ways around it, so maybe reach out personally if you hit a wall (probably isn't useful to go into it all here).

**Comment by cgnhmt** [comment]
Hi Ben, I noticed that I was using old version of Step Functions Local (_Version: 1.4.0 - Build: 2019-09-18_). 
After updating to the _Version:1.7.9 - Build: 2021-06-24_
Now, I am able to create EXPRESS workflows as you said. Thank you for the suggestions for Terraform as well.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
