### ISSUE TITLE
Manage AWS Glue Jobs with Step Functions needs to be updated

### ISSUE THREAD

**Issue by tim-pugh** [awsdocs/aws-step-functions-developer-guide#45]
https://docs.aws.amazon.com/step-functions/latest/dg/connect-glue.html -> AllocatedCapacity

this is deprecated as per: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-jobs-runs.html#aws-glue-api-jobs-runs-StartJobRun

Please update and remove AllocatedCapacity and update with MaxCapacity.

**Comment by tim-pugh** [comment]
Also: can we have more examples of all supported values?

**Comment by tim-pugh** [comment]
Below is an example of the NumberOfWorkers and WorkerType, and it has been reported as working. This would help cover examples for those two parameters:
  
    "Glue StartJobRun": {
      "Type": "Task",
      "Resource": "arn:aws:states:::glue:startJobRun.sync",
      "Parameters": {
        "JobName": "AGlueJob",
        "NumberOfWorkers": 10,
        "WorkerType": "G.1X"
      },

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
