### ISSUE TITLE
Do paths support colons?

### ISSUE THREAD

**Issue by alegonz** [awsdocs/aws-step-functions-developer-guide#47]
The [documentation of "Paths"](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-paths.html) states that:

> The operators `@ .. , : ? *` aren't supported.

But the [documentation of "InputPath, Parameters and ResultSelector"](https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html) has the following note:

> A path can yield a selection of values. Consider the following example.
> ```
> { "a": [1, 2, 3, 4] }
> ```
> If you apply the path `$.a[0:2]`, the following is the result.
> ```
> [ 1, 2 ]
> ```

**Comment by pshongwe** [comment]
it only won't work for ResultPath, because it uses Reference Path. InputPath, OutputPath etc should work fine as they use regular Paths.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
