### ISSUE TITLE
IAM principal incorrect

### ISSUE THREAD

**Issue by pshongwe** [awsdocs/aws-step-functions-developer-guide#49]
please correct documentation
```
"Principal": {
              "AWS": "arn:aws:iam:123456789012:user/MyUser"
 }
```
Should be:
```
"Principal": {
              "AWS": "arn:aws:iam::123456789012:user/MyUser"
 }
```
https://docs.amazonaws.cn/en_us/step-functions/latest/dg/vpc-iam.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
