### ISSUE TITLE
Example using S3 data dump in between steps

### ISSUE THREAD

**Issue by mthomas-github** [awsdocs/aws-step-functions-developer-guide#56]
Hello I'm trying to understand the whole writing to S3 and reading it from S3 on other steps. Is possible to provide an example, that will show how to use an S3 in step functions thanks.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
