### ISSUE TITLE
Workflow Studio documentation - page not found

### ISSUE THREAD

**Issue by DragonStuff** [awsdocs/aws-step-functions-developer-guide#61]
Looks like the links at the bottom of the Developers Guide are broken or the live state doesn't match the repo. Unfortunately, I seem to be able to find any Workflow Studio documentation on this repo (used GitHub's repository search function too).

https://docs.aws.amazon.com/step-functions/latest/dg/workflow-studio-known-limitations.html leads to https://github.com/awsdocs/aws-step-functions-developer-guide/tree/master/doc_source/workflow-studio-known-limitations.md which throws a 404.

Just wanted to submit a correction for the following:

> Some service states are not currently available in Workflow Studio. Instead, after you ~creat~ create or edit your state machine in Workflow Studio, you can use code snippets to add the state to your state machine definition. Code snippets can be found in the drop down menu on your state machine's code pane.

Let me know where I can submit an MR. Thank you!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
