### ISSUE TITLE
Lambda.TooManyRequestsException even with no concurrent lambdas

### ISSUE THREAD

**Issue by bhargav01** [awsdocs/aws-step-functions-developer-guide#74]
Whenever the step function waits for more than 5min, the next lambda in the step function fails with a Lambda.TooManyRequestsException.
I am sure that the number of lambdas called concurrently in my account won't even cross 5. This is very frustrating.

I tried removing my internal multiprocessing logic in the lambda, but the issue still persists.
I think this error is a default error.

**Comment by bhargav01** [comment]
This issue continues to happen and not sure why!!
Is there an internal lambda running in AWS, because i am sure there are no more than 5 lamdas running in parallel for my project

**Comment by bhargav01** [comment]
debugged the issue, i get this error TooManyRequestsException when i copy files from one s3 folder to another through bucket.copy()

so many issues in step functions IMO

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
