### ISSUE TITLE
EKS private endpoint access 

### ISSUE THREAD

**Issue by yanivpaz** [awsdocs/aws-step-functions-developer-guide#75]
I think that  more clarification id needed in the documentation :
https://github.com/awsdocs/aws-step-functions-developer-guide/blob/master/doc_source/connect-eks.md

its not clear if private Amazon EKS cluster endpoint can be accessed from step function .
also related 
https://aws.amazon.com/premiumsupport/knowledge-center/eks-private-cluster-endpoint-vpc/

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
