### ISSUE TITLE
Clarify intrinsic functions limitaitons

### ISSUE THREAD

**Issue by Meosit** [awsdocs/aws-step-functions-developer-guide#81]
The dedicated [intrinsic functions page](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html#asl-intrsc-func-string-operation) states that "Intrinsics are constructs that look similar to functions in programming languages", however there are no clear definition of the limitations comparing to the regular programming languages which leads to compile or runtime errors.

Two most important features that I find missing and already spent some time fixing errors are the following:

1. You cannot pass result of one function as a parameter to another:  
`{"date": "States.ArrayGetItem(States.StringSplit('2020-05-27T08:00:00.000Z', 'T'), 0)"}`
2. You cannot access the result of the function instantly within the same call:  
`{"date": "States.StringSplit('2020-05-27T08:00:00.000Z', 'T')[0]"}`

There are might be other limitations that worth mentioning (or implementing as a feature)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
