### ISSUE TITLE
DynamoDB Integration Clarification

### ISSUE THREAD

**Issue by lhendrick-t10** [awsdocs/aws-step-functions-developer-guide#82]
Hi ho!

The documentation inside Optimized Integrations > [Amazon DynamoDB](https://github.com/awsdocs/aws-step-functions-developer-guide/blob/master/doc_source/connect-ddb.md) is somewhat confusing.

There's a callout before listing the API actions that says:

> How the optimized DynamoDB integration is different than the DynamoDB AWS SDK integration
There is no optimization for the [Request Response](https://github.com/awsdocs/aws-step-functions-developer-guide/blob/master/doc_source/connect-to-resource.md#connect-default) integration pattern. The [Wait for a Callback with the Task Token](https://github.com/awsdocs/aws-step-functions-developer-guide/blob/master/doc_source/connect-to-resource.md#connect-wait-token) integration pattern is not supported. Only [https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/ API_GetItem.html](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/ API_GetItem.html), [https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/ API_PutItem.html](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/ API_PutItem.html), and [https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/ API_UpdateItem.html](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/ API_UpdateItem.html) API actions are available through optimized integration. Other API actions, such as https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html are available using the DynamoDB AWS SDK integration.

But then in the body of the documentation the DeleteItem API is also referenced. Just want to get some clarification on which is correct, I'm happy to submit a PR to update the doc either way once we have that clarification

**Comment by jpluscplusm** [comment]
I came to this repo having also noticed this discrepancy, and am rather surprised to see such an easy, low-hanging Issue unaddressed and unacknowledged by the @awsdocs team!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
